table dim_run
	column run_id
		dataType: int64
		summarizeBy: none
		sourceColumn: run_id

	column comparison_role
		dataType: string
		summarizeBy: none
		sourceColumn: comparison_role

	column model_version
		dataType: string
		summarizeBy: none
		sourceColumn: model_version

	column dataset_id
		dataType: string
		summarizeBy: none
		sourceColumn: dataset_id

	partition dim_run = m
		mode: import
		source =
			let
			    Source = MySQL.Database(MySQLServer, MySQLDatabase, [ReturnSingleDatabase=true]),
			    Rows = Source{[Schema=MySQLDatabase, Item="dim_run"]}[Data],
			    Typed = Table.TransformColumnTypes(Rows, {{"run_id", Int64.Type}, {"comparison_role", type text}, {"model_version", type text}, {"dataset_id", type text}}, "en-US")
			in
			    Typed