table data_quality
	column table_name
		dataType: string
		summarizeBy: none
		sourceColumn: table_name

	column row_count
		dataType: int64
		summarizeBy: none
		sourceColumn: row_count

	column duplicate_rows
		dataType: int64
		summarizeBy: none
		sourceColumn: duplicate_rows

	column missing_cells
		dataType: int64
		summarizeBy: none
		sourceColumn: missing_cells

	column synthetic_percentage
		dataType: double
		summarizeBy: none
		sourceColumn: synthetic_percentage

	partition data_quality = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/data_quality.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"table_name", type text}, {"row_count", Int64.Type}, {"duplicate_rows", Int64.Type}, {"missing_cells", Int64.Type}, {"synthetic_percentage", type number}}, "en-US")
			in
				Typed