table dim_corner
	column corner_id
		dataType: int64
		summarizeBy: none
		sourceColumn: corner_id

	column sector_id
		dataType: int64
		summarizeBy: none
		sourceColumn: sector_id

	column radius_m
		dataType: int64
		summarizeBy: none
		sourceColumn: radius_m

	column banking_rad
		dataType: double
		summarizeBy: none
		sourceColumn: banking_rad

	column width_m
		dataType: int64
		summarizeBy: none
		sourceColumn: width_m

	column data_source_type
		dataType: string
		summarizeBy: none
		sourceColumn: data_source_type

	column synthetic_flag
		dataType: boolean
		summarizeBy: none
		sourceColumn: synthetic_flag

	column model_version
		dataType: string
		summarizeBy: none
		sourceColumn: model_version

	column data_version
		dataType: string
		summarizeBy: none
		sourceColumn: data_version

	column generation_timestamp
		dataType: string
		summarizeBy: none
		sourceColumn: generation_timestamp

	column random_seed
		dataType: int64
		summarizeBy: none
		sourceColumn: random_seed

	column validation_status
		dataType: string
		summarizeBy: none
		sourceColumn: validation_status

	partition dim_corner = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/dim_corner.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"corner_id", Int64.Type}, {"sector_id", Int64.Type}, {"radius_m", Int64.Type}, {"banking_rad", type number}, {"width_m", Int64.Type}, {"data_source_type", type text}, {"synthetic_flag", type logical}, {"model_version", type text}, {"data_version", type text}, {"generation_timestamp", type text}, {"random_seed", Int64.Type}, {"validation_status", type text}}, "en-US")
			in
				Typed