table dim_setup
	column setup_id
		dataType: int64
		summarizeBy: none
		sourceColumn: setup_id

	column setup_name
		dataType: string
		summarizeBy: none
		sourceColumn: setup_name

	column front_wing_deg
		dataType: double
		summarizeBy: none
		sourceColumn: front_wing_deg

	column rear_wing_deg
		dataType: double
		summarizeBy: none
		sourceColumn: rear_wing_deg

	column front_height_m
		dataType: double
		summarizeBy: none
		sourceColumn: front_height_m

	column rear_height_m
		dataType: double
		summarizeBy: none
		sourceColumn: rear_height_m

	column package
		dataType: string
		summarizeBy: none
		sourceColumn: package

	column data_source_type
		dataType: string
		summarizeBy: none
		sourceColumn: data_source_type

	column synthetic_flag
		dataType: boolean
		summarizeBy: none
		sourceColumn: synthetic_flag

	column model_version
		dataType: string
		summarizeBy: none
		sourceColumn: model_version

	column data_version
		dataType: string
		summarizeBy: none
		sourceColumn: data_version

	column generation_timestamp
		dataType: string
		summarizeBy: none
		sourceColumn: generation_timestamp

	column random_seed
		dataType: int64
		summarizeBy: none
		sourceColumn: random_seed

	column validation_status
		dataType: string
		summarizeBy: none
		sourceColumn: validation_status

	partition dim_setup = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/dim_setup.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"setup_id", Int64.Type}, {"setup_name", type text}, {"front_wing_deg", type number}, {"rear_wing_deg", type number}, {"front_height_m", type number}, {"rear_height_m", type number}, {"package", type text}, {"data_source_type", type text}, {"synthetic_flag", type logical}, {"model_version", type text}, {"data_version", type text}, {"generation_timestamp", type text}, {"random_seed", Int64.Type}, {"validation_status", type text}}, "en-US")
			in
				Typed