table dim_tyre
	column tyre_id
		dataType: int64
		summarizeBy: none
		sourceColumn: tyre_id

	column name
		dataType: string
		summarizeBy: none
		sourceColumn: name

	column mu
		dataType: double
		summarizeBy: none
		sourceColumn: mu

	column wear_per_m
		dataType: double
		summarizeBy: none
		sourceColumn: wear_per_m

	column optimal_temp_c
		dataType: int64
		summarizeBy: none
		sourceColumn: optimal_temp_c

	column load_exponent
		dataType: double
		summarizeBy: none
		sourceColumn: load_exponent

	column reference_load_n
		dataType: int64
		summarizeBy: none
		sourceColumn: reference_load_n

	column data_source_type
		dataType: string
		summarizeBy: none
		sourceColumn: data_source_type

	column synthetic_flag
		dataType: boolean
		summarizeBy: none
		sourceColumn: synthetic_flag

	column model_version
		dataType: string
		summarizeBy: none
		sourceColumn: model_version

	column data_version
		dataType: string
		summarizeBy: none
		sourceColumn: data_version

	column generation_timestamp
		dataType: string
		summarizeBy: none
		sourceColumn: generation_timestamp

	column random_seed
		dataType: int64
		summarizeBy: none
		sourceColumn: random_seed

	column validation_status
		dataType: string
		summarizeBy: none
		sourceColumn: validation_status

	partition dim_tyre = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/dim_tyre.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"tyre_id", Int64.Type}, {"name", type text}, {"mu", type number}, {"wear_per_m", type number}, {"optimal_temp_c", Int64.Type}, {"load_exponent", type number}, {"reference_load_n", Int64.Type}, {"data_source_type", type text}, {"synthetic_flag", type logical}, {"model_version", type text}, {"data_version", type text}, {"generation_timestamp", type text}, {"random_seed", Int64.Type}, {"validation_status", type text}}, "en-US")
			in
				Typed