table dim_date
	column date_id
		dataType: int64
		summarizeBy: none
		sourceColumn: date_id

	column date_iso
		dataType: string
		summarizeBy: none
		sourceColumn: date_iso

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column month
		dataType: int64
		summarizeBy: none
		sourceColumn: month

	column day
		dataType: int64
		summarizeBy: none
		sourceColumn: day

	column data_source_type
		dataType: string
		summarizeBy: none
		sourceColumn: data_source_type

	column synthetic_flag
		dataType: boolean
		summarizeBy: none
		sourceColumn: synthetic_flag

	column model_version
		dataType: string
		summarizeBy: none
		sourceColumn: model_version

	column data_version
		dataType: string
		summarizeBy: none
		sourceColumn: data_version

	column generation_timestamp
		dataType: string
		summarizeBy: none
		sourceColumn: generation_timestamp

	column random_seed
		dataType: int64
		summarizeBy: none
		sourceColumn: random_seed

	column validation_status
		dataType: string
		summarizeBy: none
		sourceColumn: validation_status

	partition dim_date = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/dim_date.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"date_id", Int64.Type}, {"date_iso", type text}, {"year", Int64.Type}, {"month", Int64.Type}, {"day", Int64.Type}, {"data_source_type", type text}, {"synthetic_flag", type logical}, {"model_version", type text}, {"data_version", type text}, {"generation_timestamp", type text}, {"random_seed", Int64.Type}, {"validation_status", type text}}, "en-US")
			in
				Typed