table fact_drs_event
	column drs_event_id
		dataType: int64
		summarizeBy: none
		sourceColumn: drs_event_id

	column run_id
		dataType: int64
		summarizeBy: none
		sourceColumn: run_id

	column start_time_s
		dataType: double
		summarizeBy: none
		sourceColumn: start_time_s

	column end_time_s
		dataType: double
		summarizeBy: none
		sourceColumn: end_time_s

	column start_distance_m
		dataType: int64
		summarizeBy: none
		sourceColumn: start_distance_m

	column end_distance_m
		dataType: int64
		summarizeBy: none
		sourceColumn: end_distance_m

	column entry_speed_mps
		dataType: double
		summarizeBy: none
		sourceColumn: entry_speed_mps

	column exit_speed_mps
		dataType: double
		summarizeBy: none
		sourceColumn: exit_speed_mps

	column circuit_id
		dataType: int64
		summarizeBy: none
		sourceColumn: circuit_id

	column setup_id
		dataType: int64
		summarizeBy: none
		sourceColumn: setup_id

	column weather_id
		dataType: int64
		summarizeBy: none
		sourceColumn: weather_id

	column tyre_id
		dataType: int64
		summarizeBy: none
		sourceColumn: tyre_id

	column session_id
		dataType: int64
		summarizeBy: none
		sourceColumn: session_id

	column car_id
		dataType: int64
		summarizeBy: none
		sourceColumn: car_id

	column date_id
		dataType: int64
		summarizeBy: none
		sourceColumn: date_id

	column comparison_group
		dataType: string
		summarizeBy: none
		sourceColumn: comparison_group

	partition fact_drs_event = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/fact_drs_event.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"drs_event_id", Int64.Type}, {"run_id", Int64.Type}, {"start_time_s", type number}, {"end_time_s", type number}, {"start_distance_m", Int64.Type}, {"end_distance_m", Int64.Type}, {"entry_speed_mps", type number}, {"exit_speed_mps", type number}, {"circuit_id", Int64.Type}, {"setup_id", Int64.Type}, {"weather_id", Int64.Type}, {"tyre_id", Int64.Type}, {"session_id", Int64.Type}, {"car_id", Int64.Type}, {"date_id", Int64.Type}, {"comparison_group", type text}}, "en-US")
			in
				Typed