table fact_optimization_run
	column optimization_run_id
		dataType: int64
		summarizeBy: none
		sourceColumn: optimization_run_id

	column circuit_id
		dataType: int64
		summarizeBy: none
		sourceColumn: circuit_id

	column objective
		dataType: string
		summarizeBy: none
		sourceColumn: objective

	column seed
		dataType: int64
		summarizeBy: none
		sourceColumn: seed

	column evaluation_count
		dataType: int64
		summarizeBy: none
		sourceColumn: evaluation_count

	column data_source_type
		dataType: string
		summarizeBy: none
		sourceColumn: data_source_type

	column synthetic_flag
		dataType: boolean
		summarizeBy: none
		sourceColumn: synthetic_flag

	column model_version
		dataType: string
		summarizeBy: none
		sourceColumn: model_version

	column data_version
		dataType: string
		summarizeBy: none
		sourceColumn: data_version

	column generation_timestamp
		dataType: string
		summarizeBy: none
		sourceColumn: generation_timestamp

	column random_seed
		dataType: int64
		summarizeBy: none
		sourceColumn: random_seed

	column validation_status
		dataType: string
		summarizeBy: none
		sourceColumn: validation_status

	partition fact_optimization_run = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/fact_optimization_run.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"optimization_run_id", Int64.Type}, {"circuit_id", Int64.Type}, {"objective", type text}, {"seed", Int64.Type}, {"evaluation_count", Int64.Type}, {"data_source_type", type text}, {"synthetic_flag", type logical}, {"model_version", type text}, {"data_version", type text}, {"generation_timestamp", type text}, {"random_seed", Int64.Type}, {"validation_status", type text}}, "en-US")
			in
				Typed