table fact_telemetry
	column telemetry_id
		dataType: string
		summarizeBy: none
		sourceColumn: telemetry_id

	column run_id
		dataType: string
		summarizeBy: none
		sourceColumn: run_id

	column sample_index
		dataType: string
		summarizeBy: none
		sourceColumn: sample_index

	column speed_mps
		dataType: string
		summarizeBy: none
		sourceColumn: speed_mps

	partition fact_telemetry = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/fact_telemetry.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"telemetry_id", type text}, {"run_id", type text}, {"sample_index", type text}, {"speed_mps", type text}}, "en-US")
			in
				Typed