table fact_sector
	column sector_fact_id
		dataType: string
		summarizeBy: none
		sourceColumn: sector_fact_id

	column run_id
		dataType: string
		summarizeBy: none
		sourceColumn: run_id

	column sector_id
		dataType: string
		summarizeBy: none
		sourceColumn: sector_id

	column sector_time_s
		dataType: string
		summarizeBy: none
		sourceColumn: sector_time_s

	partition fact_sector = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/fact_sector.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"sector_fact_id", type text}, {"run_id", type text}, {"sector_id", type text}, {"sector_time_s", type text}}, "en-US")
			in
				Typed