table interventions
	column scenario
		dataType: string
		summarizeBy: none
		sourceColumn: scenario

	column initial_fuel_kg
		dataType: int64
		summarizeBy: none
		sourceColumn: initial_fuel_kg

	column initial_wear
		dataType: double
		summarizeBy: none
		sourceColumn: initial_wear

	column lap_time_s
		dataType: double
		summarizeBy: none
		sourceColumn: lap_time_s

	column circuit_id
		dataType: int64
		summarizeBy: none
		sourceColumn: circuit_id

	column setup_id
		dataType: int64
		summarizeBy: none
		sourceColumn: setup_id

	column delta_from_reference_s
		dataType: double
		summarizeBy: none
		sourceColumn: delta_from_reference_s

	partition interventions = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/interventions.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"scenario", type text}, {"initial_fuel_kg", Int64.Type}, {"initial_wear", type number}, {"lap_time_s", type number}, {"circuit_id", Int64.Type}, {"setup_id", Int64.Type}, {"delta_from_reference_s", type number}}, "en-US")
			in
				Typed