table uncertainty
	column scenario_id
		dataType: int64
		summarizeBy: none
		sourceColumn: scenario_id

	column name
		dataType: string
		summarizeBy: none
		sourceColumn: name

	column pressure_pa
		dataType: double
		summarizeBy: none
		sourceColumn: pressure_pa

	column temperature_k
		dataType: double
		summarizeBy: none
		sourceColumn: temperature_k

	column grip
		dataType: double
		summarizeBy: none
		sourceColumn: grip

	column headwind_mps
		dataType: double
		summarizeBy: none
		sourceColumn: headwind_mps

	column crosswind_mps
		dataType: double
		summarizeBy: none
		sourceColumn: crosswind_mps

	column aero_multiplier
		dataType: double
		summarizeBy: none
		sourceColumn: aero_multiplier

	column density_multiplier
		dataType: double
		summarizeBy: none
		sourceColumn: density_multiplier

	column height_offset_m
		dataType: double
		summarizeBy: none
		sourceColumn: height_offset_m

	column baseline_lap_s
		dataType: double
		summarizeBy: none
		sourceColumn: baseline_lap_s

	column candidate_lap_s
		dataType: double
		summarizeBy: none
		sourceColumn: candidate_lap_s

	column delta_s
		dataType: double
		summarizeBy: none
		sourceColumn: delta_s

	column feasible
		dataType: boolean
		summarizeBy: none
		sourceColumn: feasible

	column error
		dataType: double
		summarizeBy: none
		sourceColumn: error

	column circuit_id
		dataType: int64
		summarizeBy: none
		sourceColumn: circuit_id

	partition uncertainty = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/uncertainty.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"scenario_id", Int64.Type}, {"name", type text}, {"pressure_pa", type number}, {"temperature_k", type number}, {"grip", type number}, {"headwind_mps", type number}, {"crosswind_mps", type number}, {"aero_multiplier", type number}, {"density_multiplier", type number}, {"height_offset_m", type number}, {"baseline_lap_s", type number}, {"candidate_lap_s", type number}, {"delta_s", type number}, {"feasible", type logical}, {"error", type number}, {"circuit_id", Int64.Type}}, "en-US")
			in
				Typed