const formatTime=globalThis.AeroTime.format;
let metric='speed_mps';const metrics={speed_mps:['Speed','m/s'],downforce_n:['Downforce','N'],drag_n:['Drag','N'],acceleration_mps2:['Acceleration','m/s²'],tyre_wear:['Tyre wear','fraction'],curvature_1pm:['Curvature','1/m']};
for(const [key,v] of Object.entries(metrics)){const b=document.createElement('button');b.textContent=v[0];b.onclick=()=>{metric=key;render()};b.dataset.key=key;document.querySelector('#buttons').append(b)}
function render(){const name=selector.value,w=DATA.recommendations[name],t=DATA.traces[name],g=DATA.geometry[name];const set=(id,v)=>document.getElementById(id).textContent=v;
set('baseline',formatTime(w.baseline.lap_time_s)+ ' min:s');set('candidate',formatTime(w.candidate.lap_time_s)+ ' min:s');set('delta',formatTime(w.lap_delta_s,true)+' min:s');
const sensitivity=DATA.numerical_sensitivity?.[name];set('sensitivity-note',sensitivity?'Numerical sensitivity: candidate − baseline is '+formatTime(sensitivity.production_delta_s,true)+' min:s at '+sensitivity.production_spacing_m+' m spacing and '+formatTime(sensitivity.finer_delta_s,true)+' min:s at '+sensitivity.finer_spacing_m+' m. '+(sensitivity.production_delta_s*sensitivity.finer_delta_s<0?'The sign reverses: this setup gain is not robust.':'These are numerical comparisons, not measured validation.'):'Numerical sensitivity has not been evaluated for this dataset version. Candidate selection is nominal only.');
document.querySelector('#settings').innerHTML=Object.entries(w.setup).map(([k,v])=>'<tr><td>'+k.replaceAll('_',' ')+'</td><td>'+(typeof v==='number'?v.toFixed(k.includes('height')?4:2):v)+'</td></tr>').join('');
set('constraints','Python model interactive-2.0 · run '+w.dataset_id.slice(0,12));
document.querySelector('#sectors').innerHTML=w.sector_comparison.map(s=>'<tr><td>'+(s.sector_id%10)+'</td><td>'+formatTime(s.sector_time_s_baseline)+'</td><td>'+formatTime(s.sector_time_s_candidate)+'</td><td>'+formatTime(s.delta_s,true)+'</td></tr>').join('');
document.querySelector('#search').innerHTML=[...w.search].sort((a,b)=>a.lap_time_s-b.lap_time_s).map(r=>'<tr><td>'+r.comparison_role+'</td><td>'+r.run_id+'</td><td>'+formatTime(r.lap_time_s)+'</td><td>'+(r.max_speed_mps*3.6).toFixed(1)+'</td><td>'+(r.tyre_wear_change*100).toFixed(3)+'</td></tr>').join('');
document.querySelectorAll('button[data-key]').forEach(b=>b.classList.toggle('active',b.dataset.key===metric));
Plotly.react('plot',['baseline','candidate'].map(role=>({x:t[role].distance_m,y:t[role][metric],name:role,mode:'lines',line:{color:role==='baseline'?'#8695a4':'#69b4f7',width:2}})),{paper_bgcolor:'#10263d',plot_bgcolor:'#10263d',margin:{t:25,r:15,b:55,l:65},xaxis:{title:{text:'Distance (m)'}},yaxis:{title:{text:metrics[metric][0]+' ('+metrics[metric][1]+')'}},legend:{orientation:'h',y:1.15},font:{family:'system-ui',color:'#dce7f2'}},{responsive:true,displaylogo:false});
const a=t.candidate;Plotly.react('map',[1,2,3].map((s)=>{const ids=a.sector_id.map((v,i)=>v%10===s?i:-1).filter(i=>i>=0);return {x:ids.map(i=>a.x_m[i]),y:ids.map(i=>a.y_m[i]),mode:'lines',name:'Sector '+s,line:{width:5,color:['#69b4f7','#e39d39','#3a9d83'][s-1]}}}),{paper_bgcolor:'#10263d',plot_bgcolor:'#10263d',font:{color:'#dce7f2'},margin:{t:20,r:20,b:55,l:65},xaxis:{title:{text:'East (m)'}},yaxis:{title:{text:'North (m)'},scaleanchor:'x',scaleratio:1},legend:{orientation:'h',y:1.15}},{responsive:true,displaylogo:false});
set('traceNote',a.distance_m.length+' samples per run; '+g.length_m.toFixed(1)+' m processed lap. Final interval closes the loop.');set('source-summary',g.source.data_source+' · '+g.source.source_license+' · SHA256 '+g.source.snapshot_sha256);set('source',JSON.stringify({geometry:g.source,processing:g.metadata,baseline:w.baseline,candidate:w.candidate},null,2));}
