// Research presentation consumes the exact committed API response.
const Research = (()=>{
 const tips={front_wing_deg:'More angle increases model downforce and drag; shifts front aero load.',rear_wing_deg:'More angle increases model downforce and drag; straight speed may fall.',front_height_m:'Departing from 0.040 m reduces assumed floor effectiveness; no suspension/bottoming model.',rear_height_m:'Departing from 0.060 m reduces assumed floor effectiveness; no suspension/bottoming model.',diffuser_efficiency:'Dimensionless multiplier. Scales floor lift; efficiency away from 1 also adds a small drag penalty.',mass_kg:'Mass excludes fuel. More mass increases inertia and lateral force demand.',fuel_load_kg:'Adds constant mass. Fuel consumption is not simulated.',air_temperature_c:'Changes air density at fixed sea-level pressure; affects both cars.',track_temperature_c:'Grip peaks at assumed 30 °C; departures reduce grip and increase wear proxy for both cars.',wind_speed_mps:'Changes relative longitudinal airspeed; crosswind side forces are omitted. Shared weather.',wind_direction_deg:'Direction wind comes FROM, clockwise from north; affects both cars.',tyre_compound:'Soft: higher assumed grip and wear. Hard: lower grip and wear. Allowed: soft, medium, hard; categorical, no unit.'};
 const descriptions={baseline:'Reference setup, medium tyres and 30 kg fuel.',low:'Low drag: expected better straight-line speed, lower cornering grip.',high:'High downforce: expected stronger cornering grip, more drag.',saved:'Restores the setup saved locally in this browser.'};
 const names={front_wing_deg:'front wing',rear_wing_deg:'rear wing',front_height_m:'front ride height',rear_height_m:'rear ride height',diffuser_efficiency:'diffuser efficiency',mass_kg:'vehicle mass',fuel_load_kg:'fuel',tyre_compound:'tyres'};
 const unit={front_wing_deg:'°',rear_wing_deg:'°',front_height_m:' m',rear_height_m:' m',mass_kg:' kg',fuel_load_kg:' kg',diffuser_efficiency:''};
 const text=(id,value)=>document.getElementById(id).textContent=value;
 function draftUpdate(){if(!catalogue)return;const p=draft(),base={...catalogue.defaults,...Object.fromEntries(Object.keys(selectedCircuit().default_weather).map(k=>[k,p[k]]))},changes=[];
   for(const [key,input] of Object.entries(fieldInputs)){const changed=p[key]!==base[key];input.closest('.setup-field').classList.toggle('changed',changed);if(changed){const delta=typeof p[key]==='number'?p[key]-base[key]:null;changes.push((names[key]||key)+' '+(delta===null?p[key]:(delta>=0?'+':'')+Number(delta.toFixed(4))+(unit[key]||'')));}}
   text('change-summary',changes.length?'Candidate changes: '+changes.join(', '):'No setup changes detected. Candidate matches baseline.');
   const warnings=[];if(Math.abs(p.front_wing_deg-p.rear_wing_deg)>18)warnings.push('Large wing imbalance: the model does not validate handling stability.');if(p.front_height_m<=.025||p.rear_height_m<=.025||p.rear_height_m<p.front_height_m)warnings.push('Extreme ride height/rake: bottoming and suspension effects are omitted.');if(p.mass_kg<750)warnings.push('Low assumed mass: not a claim about a regulation-compliant car.');if(p.wind_speed_mps>10)warnings.push('Strong wind: crosswind forces and gusts are omitted.');if(p.track_temperature_c<10||p.track_temperature_c>50)warnings.push('Extreme track temperature: grip is an uncalibrated approximation.');if(p.diffuser_efficiency>1.2)warnings.push('High diffuser effectiveness is an optimistic model assumption.');
   text('setup-warnings',warnings.length?'Assumption warnings (non-blocking): '+warnings.join(' '):'');
   const c=selectedCircuit().id,suggest=['monza','spa'].includes(c)?'Low drag':c==='monaco'?'High downforce':c==='suzuka'?'High downforce':'Baseline';
   text('preset-description',descriptions[document.querySelector('#preset').value]);text('preset-note','Model recommendation: explore '+suggest+' for '+selectedCircuit().name+'. Circuit-character heuristic, not an optimized result or real engineering advice. Weather changes apply to both cars.');
 }
 function init(){for(const [key,input] of Object.entries(fieldInputs)){const parent=input.closest('.setup-field'),detail=document.createElement('details'),summary=document.createElement('summary'),help=document.createElement('p');summary.textContent='Parameter help';const range=catalogue.fields[key];help.id='help-'+key;help.textContent=tips[key]+(range?' Allowed range '+range[0]+'–'+range[1]+'; unit shown in the parameter label.':'');detail.append(summary,help);parent.append(detail);input.title=help.textContent;input.setAttribute('aria-describedby',help.id);const slider=document.getElementById('range-'+key);if(slider){slider.title=help.textContent;slider.setAttribute('aria-describedby',help.id);}}
   document.querySelector('#setup-form').addEventListener('input',draftUpdate);document.querySelector('#setup-form').addEventListener('change',draftUpdate);
   document.querySelector('#reset-candidate').onclick=()=>fill({...catalogue.defaults,...Object.fromEntries(Object.keys(selectedCircuit().default_weather).map(k=>[k,draft()[k]]))});draftUpdate();
 }
 const roles=['baseline','candidate'],colors=['#a7b7c6','#69b4f7'];
 const pendingCharts=new Map();
 const chartObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting&&pendingCharts.has(entry.target.id)){const args=pendingCharts.get(entry.target.id);pendingCharts.delete(entry.target.id);drawChart(...args);}}},{rootMargin:'200px'});
 document.querySelectorAll('.research-chart').forEach(el=>chartObserver.observe(el));
 function chart(...args){const el=document.getElementById(args[0]),box=el.getBoundingClientRect();if(box.height&&box.bottom>=-200&&box.top<innerHeight+200){pendingCharts.delete(args[0]);drawChart(...args);}else pendingCharts.set(args[0],args);}
 function drawChart(id,series,xlabel,ylabel,extra={}){series=series.filter(s=>Array.isArray(s.x)&&Array.isArray(s.y)&&s.x.length===s.y.length&&s.y.length);if(!series.length)extra={...extra,annotations:[{text:'No data available for this run',showarrow:false,xref:'paper',yref:'paper',x:.5,y:.5}]};Plotly.react(id,series,{paper_bgcolor:'#10263d',plot_bgcolor:'#10263d',font:{color:'#dce7f2',family:'system-ui'},margin:{t:25,r:25,b:65,l:75},showlegend:true,legend:{orientation:'h',y:1.18},xaxis:{title:{text:xlabel},gridcolor:'#294258'},yaxis:{title:{text:ylabel},gridcolor:'#294258',zerolinecolor:'#9bafbf'},...extra},{responsive:true,displaylogo:false});}
 function render(){const name=selector.value,w=DATA.recommendations[name],ts=DATA.traces[name],comparison=w?.comparison;if(!comparison){text('insights-list','Comparison details are unavailable for this run.');return;}
   const ul=document.getElementById('insights-list');ul.replaceChildren(...comparison.insights.map(v=>{const li=document.createElement('li');li.textContent=v;return li;}));
   text('winner',comparison.winner);text('winner-detail','Candidate − baseline '+globalThis.AeroTime.format(w.lap_delta_s,true)+' min:s · predicted result only');document.getElementById('winner-card').className='metric '+(Math.abs(w.lap_delta_s)<.0005?'neutral':w.lap_delta_s<0?'gain':'loss');
   const rows=[['Maximum speed','km/h',r=>r.max_speed_mps*3.6],['Average speed (distance / lap time)','km/h',r=>r.average_speed_kmh],['Mean total-car downforce (time weighted)','N',r=>r.mean_downforce_n],['Mean total-car drag (time weighted)','N',r=>r.mean_drag_n],['Downforce impulse over lap','kN·s',r=>r.downforce_impulse_ns/1000],['Drag work over lap','MJ',r=>r.drag_work_j/1e6],['Tyre degradation proxy change','%',r=>r.tyre_wear_change*100]];
   const table=document.getElementById('result-summary');table.replaceChildren();for(const [label,units,get] of rows){const tr=document.createElement('tr');for(const value of [label,units,...roles.map(role=>Number.isFinite(get(w[role]))?get(w[role]).toFixed(3):'Unavailable')]){const td=document.createElement('td');td.textContent=value;tr.append(td);}table.append(tr);}
   text('confidence-detail',roles.map(role=>role+': '+(w[role].confidence||'Unavailable')).join(' · ')+'. No measured error interval is available. Small gains can change with spatial resolution; this run has no mesh-sensitivity check.');
   const lines=(x,y,scale=1)=>roles.map((role,i)=>({x:ts[role][x],y:ts[role][y]?.map(v=>v*scale),name:role,mode:'lines',line:{color:colors[i],width:2}}));
   chart('speed-comparison',lines('distance_m','speed_mps',3.6),'Lap distance (m)','Speed (km/h)');
   chart('delta-distance',[{x:comparison.distance_m,y:comparison.cumulative_delta_s,name:'Candidate − baseline',mode:'lines',line:{color:'#69b4f7'}}],'Lap distance (m)','Cumulative delta (s)');
   chart('sector-delta',[{x:w.sector_comparison.map(s=>'S'+s.sector_id%10),y:w.sector_comparison.map(s=>s.delta_s),name:'Candidate − baseline',type:'bar',text:w.sector_comparison.map(s=>(s.delta_s>=0?'+':'')+s.delta_s.toFixed(3)+' s'),textposition:'outside',cliponaxis:false,marker:{color:w.sector_comparison.map(s=>Math.abs(s.delta_s)<.0005?'#a7b7c6':s.delta_s<0?'#2acb9a':'#ee9765')}}],'Analytical sector','Delta (s)');
   for(const [id,field,color] of [['df-speed','downforce_n','#24cfba'],['drag-speed','drag_n','#e5ae61']])chart(id,roles.map((role,i)=>({x:ts[role].speed_mps.map(v=>v*3.6),y:ts[role][field],name:role,mode:'markers',marker:{size:i?4:3,opacity:.55,color:i?color:colors[0],symbol:i?'circle':'cross'}})),'Ground speed (km/h)',field==='drag_n'?'Drag (N)':'Total-car downforce (N)');
   const t=ts.candidate,delta=comparison.cumulative_delta_s.slice(0,-1),bound=Math.max(.001,...delta.map(Math.abs));
   chart('gain-map',[{x:[...t.x_m,t.x_m[0]],y:[...t.y_m,t.y_m[0]],mode:'lines',name:'Mapped centreline',line:{color:'#718294',width:2},hoverinfo:'skip'},{x:t.x_m,y:t.y_m,customdata:t.distance_m,mode:'markers',name:'Cumulative delta',marker:{size:5,color:delta,cmin:-bound,cmax:bound,colorscale:[[0,'#2acb9a'],[.5,'#c4d0dc'],[1,'#ee9765']],colorbar:{title:{text:'Δ time (s)'},thickness:12}},hovertemplate:'Distance %{customdata:.0f} m<br>Candidate − baseline %{marker.color:+.3f} s<extra></extra>'}],'East (m)','North (m)',{yaxis:{title:{text:'North (m)'},scaleanchor:'x',scaleratio:1},margin:{t:35,l:65,b:60,r:95}});
   document.querySelectorAll('[data-csv]').forEach(b=>b.disabled=false);
 }
 function csvRows(kind){return globalThis.AeroExports.rows(DATA,selector.value,kind);}
 function downloadCSV(kind){const rows=csvRows(kind);if(!rows.length){status('No completed run available to export.',true);return;}const data=globalThis.AeroExports.serialize(rows);const url=URL.createObjectURL(new Blob(['\ufeff'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='aero-lab-'+activeId+'-'+kind+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 window.addEventListener('aero-data',render);
 document.querySelectorAll('[data-csv]').forEach(b=>b.onclick=()=>downloadCSV(b.dataset.csv));
 document.getElementById('analysis-tab').addEventListener('click',()=>requestAnimationFrame(()=>document.querySelectorAll('.research-chart').forEach(el=>{if(el.data)Plotly.Plots.resize(el);}))); 
 return {init,draftUpdate,render,csvRows};
})();
